- vars/cosaPod.groovy
- vars/fcosBuild.groovy
- vars/fcosKola.groovy
- vars/pod.groovy
- vars/shwrap.groovy
We can do this now that the projectatomic-ci is dead!
> Merge coreos ci branch

- vars/fcosKola.groovy
rpm-ostree still isn't running the external tests, I think
we need this.
> fcosKola: Fix check for tests/kola

- vars/fcosBuild.groovy
Just like bc38041258f4d3f0e79bd97cfb1766c4f8562858.
> fcosBuild: add extraArgs

- vars/pod.groovy
Part of the series on standardizing on coreos-ci-lib in production. We
have this intermediate world right now where all the secrets are being
mounted into all pod invocations, which doesn't really make sense. As an
intermediate step, let's allow mounting only the secrets we actually
need into the pod.
Eventually though we should use native Jenkins credentials so that we
only have access to the secrets for the specific steps we need.
> pod: add support for mounting secrets

- vars/fcosKola.groovy
```
commit e757aa46f0cc60e2ab572cb6f3da5f0bcda2cdfb
Date:   Thu Oct 22 15:24:15 2020 -0400
fcosKola: add `build` parameter
Make this a separate parameter instead of having to pass it through
`extraArgs` because it needs to be used in both `run` and
`run-upgrade`.
commit 937721dd79593d79e22dda3982e400138a1ecbc4
Date:   Thu Oct 22 15:25:06 2020 -0400
fcosKola: add `platformArgs` parameter
Similarly to the previous commit, add a separate `platformArgs`
parameter since we want to pass this to `kola` in both the `run` and
`run-upgrade` branches.
```
> fcosKola: add `build` and `platformArgs` parameters

- vars/fcosKola.groovy
Add getCosaDir to reflect new function in utils
> fcosKola: Reflect utils

- vars/fcosKola.groovy
> fcosKola: Add basic qemu scenarios

- vars/pod.groovy
We'll need this in order to move from the old world (of hardcoding
everything in a `pod.json` file in the git repo) to the new world (where
we only mount what we actually need for a given pod).
> pod: add support for configMaps

- vars/fcosKolaTestIso.groovy
Make testLive available in utils
> utils: Add testLive

- vars/utils.groovy
Add cosa_cmd in order to easily run cosa commands
> utils: Add cosaCmd

- vars/cosaParallelCmds.groovy
Make fcosCosaBuildMetal available as a custom step
> Add cosaParallelCmds.groovy

- vars/fcosKola.groovy
> fcosKola: add `addExtTests` parameter

- vars/pod.groovy
See https://github.com/coreos/coreos-ci/issues/23
We're doing this manually in rpm-ostree CI; let's standardize
on this.
> Automatically set MAKE_JOBS

- vars/utils.groovy
Upstreamed from
https://github.com/coreos/fedora-coreos-pipeline/blob/5cf784ba931627c1c08dbb9f09080c57542480c9/utils.groovy#L63.
> utils: add pathExists

- vars/buildImage.groovy
- Fail buildImage if image build fails
> Issue #63 - Fix buildImage

- resources/com/github/coreos/job.yaml
See individual commit messages.
> job.yaml: add some documentation and bump sleep to 24h

- vars/gangplank.groovy
- Add a helper to facilitate gangplank calls
> Add gangplank helper

- vars/gangplank.groovy
> Fix function names and documentation

- vars/buildImage.groovy
The way we use `watch`, the closure only runs once and then exits. But
we want to keep watching for changes until the build goes to `Complete`.
Instead, just use `untilEach()` which is nicer for this. This mirrors
the last example in:
https://github.com/openshift/jenkins-client-plugin#watching-and-waiting-of-course
Also add a build timeout of 2 hours to be safe.
> buildImage: use untilEach() instead of watch() and add timeout

- vars/pod.groovy
> Fix serviceAccount declaration in pod

- vars/gangplank.groovy
> gangplank: Add bucket option to gangplank

- vars/gangplank.groovy
- We need to pass the image name and the bucket it is using
> gangplank: Fix finalize call

- vars/fcosKolaTestIso.groovy
In each case, run a minimal test set by default.
Untested.
> fcosKolaTestIso: also test on UEFI, UEFI + Secure Boot, multipath

- vars/gangplank.groovy
> gangplank: Fix missing trailing space in function

- vars/fcosKola.groovy
Reruns are off by default in kola. Lets enable them by default here and add an  
option to disable them
> fcosKola: add disableRerun option

- vars/fcosKola.groovy
Otherwise it's global state.
Likely to resolve https://github.com/coreos/coreos-ci-lib/issues/95.
> fcosKola: make `kolaRuns` local

- vars/fcosKola.groovy
If we try to run mutliple fcosKola() invocations in parallel they
step on each others output directory. Let's write somewhere unique.
> fcosKola: use a unique output directory for each run

- vars/fcosKola.groovy
Previously if a Jenkins run executed multiple fcosKola calls it would
run multiple times but there would only be one archived kola.tar.xz at
the end of the run because each run overwrote the previous one. Generate
some unique characters to add to the filename of each uploaded file. Also
allow the caller to pass in a marker that will be added to the uploaded
filenames to make them more identifiable.
> fcosKola: make archived artifact filenames unique

- vars/pod.groovy
Setting the `serviceAccountName` field in the pod YAML itself is not
working with the kubernetes plugin. I noticed that `podTemplate` also
supports specifying the `serviceAccount` directly. It's possible that
that key is used and any service account set in the pod YAML directly is
always overridden.
Let's try using that instead.
> pod: set serviceAccount in podTemplate instead of YAML

- vars/buildImage.groovy
In cosa CI, we're hitting:
> runtime: failed to create new OS thread
I think this is another instance of non-Kubernetes-aware multiprocessing
like in https://github.com/coreos/coreos-ci/issues/23.
Let's expose the `resources` knob for building images like we already do
for `pod`. This will allow us in cosa to request a specific amount, and
then asking golang to respect it.
> buildImage: add support for setting memory and cpu

- vars/kolaTestIso.groovy
- vars/utils.groovy
This function will behave the same as jenkins parallel but will only run `max` number of runs in parallel at once.
> utils: add runParallel() function

- .github/CODEOWNERS
Saqib is no longer an owner of this repo.
> CODEOWNERS: drop saqibali-2k

- vars/kolaTestIso.groovy
- Clean up code to reflect changes done in kola testiso in coreos-assembler
> kolaTestIso: Update to reflect new kola testiso in coreos-assembler

- vars/pod.groovy
- vars/shwrap.groovy
- vars/shwrapCapture.groovy
- vars/shwrapRc.groovy
That way we're sure it's always set.
> Set `HOME` at the pod level instead of in shwrap helpers

- vars/pod.groovy
- Add option for mounting secrets using subpath in /etc;
- Change the mountpath if it is a brew-ca certificate
> pod: Add secret subpath

- vars/checkoutToDir.groovy
Prep for adding a git submodule to fedora-coreos-config.
> checkoutToDir: Recurse submodules

- vars/pod.groovy
We'll set NAME=VALUE for each requested environment variable.
Part of https://github.com/coreos/fedora-coreos-pipeline/issues/939
> pod: support setting env vars in the pod
