coreos/coreos-ci-lib

- vars/coreos.groovy
I think this is better than calling it `privileged` as that
has a specific meaning in Docker/Kubernetes.
See my argument at https://lwn.net/Articles/796885/
> pod: Support `runAsUser: 0`

- vars/coreos.groovy
This is the classic "handle 'falsy' values in dict lookup" problem. We
need to compare against `null` to actually check for existence in the
map in case the value is `0`.
> pod: fix map lookup for `runAsUser: 0`

- vars/coreos.groovy
E.g. in rpm-ostree CI, I'd like to be able to request 8G so we can stand
up a couple of VMs for testing.
Similarly, for coreos-assembler and fedora-coreos-config, I'd like to
run kola tests in parallel.
> pod: add support for memory requests

- vars/coreos.groovy
Going to use this in rpm-ostree CI.
The `.toString()` there is necessary. Otherwise, Groovy gets super
confused and interprets the values as an array of different types.:
```
resources:
requests:
cpu:
bytes:
- 54
strings:
- ''
- ''
valueCount: 1
values:
- 6
```
Possibly Groovy's loose type system gone wrong?
> pod: add support for cpu requests

- vars/coreos.groovy
This causes an unknown parameter warning:
WARNING: Unknown parameter(s) found for class type
'org.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStep':
defaultContainer
> coreos.groovy: drop defaultContainer field

- vars/coreos.groovy
Let's designate `/srv` as the place where CI work that needs a real
filesystem and does lots of IO can operate.
> coreos.groovy: always mount emptyDir on /srv

- vars/cosaPod.groovy
- vars/fcosBuild.groovy
- vars/fcosKola.groovy
- vars/pod.groovy
- vars/shwrap.groovy
This changes in significant ways how this shared library is set up.
First, I re-read the documentation on shared libraries more closely and
we now follow conventions like having custom steps use a `call()`
function.
But also, there is now a much bigger emphasis on the `cosa build`
workflow. For example, there is now a `cosaPod` which default to the
cosa image.
There's a `buildroot` parameter one can use to request the buildroot
image instead (and of course, there's a lower-level `pod` step for full
control).
There is also a `fcosBuild` custom step, which will automatically build
FCOS, optionally building and/or layering some directories, then run
`cosa kola`.
> Add more custom steps, streamline cosa build + kola workflow

- vars/fcosBuild.groovy
Sometimes the procedure to set up the cosa workdir can be more complex
depending on what we're testing. Allow callers to skip the `cosa init`
implicitly done here.
> fcosBuild: add skipInit parameter

- vars/fcosKola.groovy
No reason not to do this always especially since we basically get it for
free timewise (we run it in parallel to the main run, which normally
takes longer anyway).
> fcosKola: also run upgrade tests by default

- vars/shwrapRc.groovy
So you can do things like `test -s foobar` more easily.
Upstreamed from fedora-coreos-pipeline.
> Add shwrapRc helper function

- vars/fcosKola.groovy
So we can use `-E` in CI, see
https://github.com/coreos/coreos-assembler/pull/1252
> fcosKola: Automatically pick up tests/kola 

- vars/fcosKola.groovy
This started failing in the fedora-coreos-config CI.
> fcosKola: Avoid duplicate registration of tests/kola

- vars/fcosKola.groovy
In `next-devel` right now, we don't have a previous build yet, so
`run-upgrade` doesn't know what parent build to use. There's a good
argument here that we could use the `testing-devel` stream as the
starting stream for now (and actually, that's something that we should
enhance our CI to cover anyway, even when we *do* have `next-devel`
parent builds, since that mimics what nodes will eventually do).
But I just want to get `next-devel` off the ground for now. The first
step either way is allowing us to skip upgrade testing here so that we
can run it manually with more options as needed.
> fcosKola: allow skipping upgrade tests

- vars/fcosKola.groovy
So we can choose to run just e.g. `ext.*` in CI runs for projects
to run just their own tests.
> fcosKola: Add tests parameter

- vars/fcosBuild.groovy
We always want to build in strict mode for CI. See:
https://github.com/coreos/fedora-coreos-tracker/issues/454
> fcosBuild: use `cosa build --strict`

- vars/fcosBuild.groovy
Doing `cosa build` directly without fetching normally works, though that
broke recently. Let's just do an explicit `fetch` for now.
See also https://github.com/coreos/coreos-assembler/pull/1379.
> fcosBuild: do a fetch first

- vars/fcosBuild.groovy
Similar to `extraArgs` but for `cosa fetch`. Sadly, building and testing
software is complex and there's always going to be corner cases that
burst through our nice and clean abstractions.
> fcosBuild: add extraFetchArgs

- vars/cosaPod.groovy
I had done this temporarily in the `.cci.jenkinsfile` of Ignition in
https://github.com/coreos/ignition/pull/976 to help debugging and I
found it really useful.
Let's just always write it out. But don't error out if it somehow
doesn't exist.
> cosaPod: write out details about cosa version

- vars/shwrap.groovy
Normally, we're running unprivileged and so Jenkins' setting of `HOME=/`
is not really helpful when running apps like `cargo` and `go build`
which expect to be able to cache things in the homedir.
If for whatever reason someone does want the default `HOME=/` behaviour,
they can just use the less opinionated `sh` step.
> shwrap: set HOME to WORKSPACE

- vars/shwrap.groovy
E.g. we don't want to override it if `$HOME` is correctly set.
> shwrap: only set HOME if unset or /

- vars/pod.groovy
The default is 100s, which is too short if the cluster is under load and
e.g. the image takes time to download, etc...
> pod: bump timeout from jnlp to 300s

- vars/pod.groovy
In newer OpenShifts, we have KubeVirt now instead of oci-kvm-hook to
express nodes which need VM access.
> pod: move to kubevirt

- resources/com/github/coreos/pod.json
- vars/pod.groovy
Instead, let the Kubernetes Jenkins plugin inject the default jnlp
container to use so that we're sure it's always using one that's made
for the given k8s version and plugin version.
This is causing issues on the new cluster where the `sh` step would
hang. It seems to be related to running on new k8s but old Jenkins, and
some kind of conflict with how working directories have changed. For
more details, see:
https://issues.jenkins-ci.org/browse/JENKINS-58777
https://issues.jenkins-ci.org/browse/JENKINS-58766
> pod: drop hardcoded jnlp container

- vars/cosaPod.groovy
- vars/pod.groovy
Let's use `dumb-init` by default for cosa pods so that we don't end up
with a swarm of zombies taking up resources.
I have a feeling this might also be contributing to the ulimit
exhaustion we're seeing in CI after the move to the new OCP 4.4 cluster.
See also https://github.com/kubernetes/kubernetes/issues/84210.
> cosaPod: spawn container with dumb-init

- vars/shwrap.groovy
We never want a 0 umask; it can e.g. cause world writable directories
which triggers failures in e.g. ostree's CI tests.
> shwrap: Fix umask if it's not set

- vars/shwrap.groovy
This reverts commit 45762ba5aded40365a4777cfa462e76b737f60ad.
This is fixed now in the cluster:
https://pagure.io/centos-infra/issue/48
> Revert "shwrap: Fix umask if it's not set"

- vars/shwrapCapture.groovy
This is a variant on shwrap() which returns the output of the command.
Part of draining helper functions from the pipeline into the library in
prep for modeling the pipeline jobs after upstream CI.
> Add shwrapCapture() step

- vars/shwrap.groovy
This reverts commit b8e563b1642dbdc10d5669e4c906a58e22dfbc3f.
Looks like we're hitting this again, so let's add it as a short-term
workaround.
> Revert "Revert "shwrap: Fix umask if it's not set""

- vars/pod.groovy
That way the closure doesn't have to create its own Groovy variable, or
rewrite the full path multiple times.
The substitution is pretty simple: we swap all dashes to underscores,
and make it all uppercase. So `aws-fcos-builds-bot-config` would become
`AWS_FCOS_BUILDS_BOT_CONFIG`.
> pod: automatically generate env vars for secret paths

- vars/checkoutToDir.groovy
This is a thin wrapper around `checkout` which makes it easy to check
out the repo into a subdirectory instead of directly into the workspace.
This can be useful especially in the context of kola external tests,
which use the directory name as part of the test name and you'd prefer a
short predictable name rather than Jenkins' long workspace name.
> Add checkoutToDir helper step

- vars/fcosBuild.groovy
- vars/utils.groovy
- Add `cosaDir` parameter to be used across multiples CIs
making it usefull to change cosa working directory
- Add getCosaDir in utils as a place with common
functions used in CI
> fcosBuild: Add `cosaDir`parameter and getCosaDir

- vars/fcosKola.groovy
These stage labels aren't actually getting rendered. Instead, the branch
name is used, which is good enough. So let's simplify this.
> fcosKola: don't nest branches in "stage"

- vars/fcosBuild.groovy
Right now, upstream CI runs might not build the OSTree if nothing
actually changed since the last pipeline build we `buildprep` from (this
can happen pretty easily today because of a bug in rpm-ostree which
causes us to not include the overlays in the state checksum:
https://github.com/coreos/rpm-ostree/pull/2310).
We could try to detect this and e.g. fetch the artifacts from the
previous build, but for CI runs, we really want to always build from
scratch anyway to be safe and make it more deterministic.
Noticed this while reviewing
https://github.com/coreos/fedora-coreos-config/pull/731 whose `cosa
build` command currently outputs:
```
No apparent changes since previous commit; use --force-nocache to override
commit: 104cb15f0154ffad59e320ef491d9b4f60de30e56ab601279fc9e30a36b01999 image: …
```
> fcosBuild: default to forcing a build

- vars/fcosBuild.groovy
In order to be more flexible across the CIs
remove the `--strict` default option. And let
who is calling it define the parameters.
We have cases where we don't want to use
`--strict`.
> Change default cosa --strict parameter

- resources/com/github/coreos/buildconfig.json
- resources/com/github/coreos/job.yaml
- vars/buildImage.groovy
Create a buildconfig and trigger the build for
coreos-assembler creating a imageStream for it.
It allows us to split the build process in 2 phases.
The coreos-assembler build will be done via DockerFile
the same way we have in most of our CIs today.
> Add buildImage

- vars/buildPod.groovy
- vars/cosaPod.groovy
We're moving away from a buildroot image based on cosa to one based on
FCOS:
https://github.com/coreos/fedora-coreos-config/pull/740
Correspondingly, add a new `buildPod` as a thin sugar for selecting that
image.
> Drop support for `cosaPod(buildroot: true)`; add `buildPod`

- vars/buildPod.groovy
- vars/pod.groovy
I think this may be the cause of failure, but I'm not totally sure.
I also added `buildPod` in the file because otherwise grep doesn't
find it.
> Explicitly parse param for stream

- vars/buildPod.groovy
I think otherwise Groovy doesn't know that it's a string for some
reason and keeps it as an array of different element types or something.
> buildPod: explicitly cast image to string

- vars/buildPod.groovy
Otherwise, we risk running out of resources in our pods.
> buildPod: use dumb-init by default

- vars/buildPod.groovy
So it's easier to test alternative images; motivated by
https://github.com/coreos/fedora-coreos-config/pull/932
> buildPod: Support overriding image

- vars/pod.groovy
- In order to run gangplank we need to use jenkins
service account, let's allow this option in pod
> pod: Add param sa (serviceAccount) in pod

- vars/fcosBuild.groovy
- It will always point to the main branch even
if we are running the CI for other branches.
For this case we need to match the fedora-coreos-config
branch with the CI branch running.
> fcosBuild: Fix branch reference

- vars/fcosBuild.groovy
This reverts commit 64916e000d007716fe18a2d13766cba8e81b3f3a.
This is breaking coreos-assembler CI:
https://github.com/coreos/coreos-ci-lib/pull/79#issuecomment-848119026
But also this seems overly specific to coreos-assembler and how that
repo and the fedora-coreos-config repo is set up.
We should probably instead in those cases leverage `skipInit` where
needed to have full control over what branches we want to check out.
> Revert "fcosBuild: Fix branch reference"

- vars/gangplank.groovy
Adds runSingleCmd and error checking for runSpec. Also adds
`getGangPlankFCOSAARCH64Params()` with a default set of params for
running against the FCOS AARCH64 builder and
`gangPlankFCOSAARCH64BuilderWrapper()` with default setup and
invocation for executing gangplank against that builder.
> gangplank: additions to aid in FCOS AARCH64 building

- vars/fcosKola.groovy
This is useful when we're running cloud tests against a different
architecture than the cosa environment we're running in. For example,
running AWS aarch64 AMI tests.
> fcosKola: support an `arch` parameter for target architecture

- vars/fcosKolaTestIso.groovy
Fixes https://github.com/coreos/coreos-ci-lib/pull/88.
> fcosKolaTestIso: fix name of `iso-as-disk` scenario

- vars/fcosKola.groovy
They provide basic coverage of several boot environments that we may not otherwise test.
> fcosKola: run basic scenarios by default

- vars/fcosKola.groovy
That should make the Blue Ocean view less messy.
Related: https://github.com/coreos/coreos-ci-lib/issues/95
> fcosKola: don't use `parallel` for single runs

- vars/fcosKola.groovy
Jenkins is complaining about `it` already existing, which I'm not sure
why. I don't see it existing elsewhere, and the overall pattern works
fine when manually testing in the Jenkins script console. Let's just try
instead using the `k, v` pattern.
Fixes: #96
> fcosKola: don't use `it` variable

- vars/gangplank.groovy
We're suspecting that the gangplank command may be exiting 0 even when
test failures occurred. Add an echo after to check this: if it's printed
then it must mean that `shwrap` didn't throw an exception.
> gangplank: print message if command finished cleanly

- vars/pod.groovy
That service account has `RunAsAny` caps.
This is a bit hacky. Ideally, this shared lib wouldn't hardcode things
specific to either CoreOS CI or the pipeline here and instead we'd store
this config in https://github.com/coreos/coreos-ci. This works though
because the FCOS pipeline doesn't use `runAsUser` at all.
> pod: use `coreos-ci-sa` serviceAccount when using `runAsUser`

- vars/pod.groovy
The latter is deprecated. It should still work at the k8s level, but
it's possible there's something going on with the Jenkins kubernetes
plugin not handling this correctly.
> pod: use serviceAccountName instead of serviceAccount

- vars/buildPod.groovy
- vars/cosaPod.groovy
The latter mirrors to the former, but it's a periodic that runs every
hour. So let's just use the images directly from app.ci for faster
iteration.
> Move from Quay.io to app.ci

- vars/pod.groovy
Right now, we're not setting any CPU limit in the pods we schedule. This
means our workloads runs without constraints and can hog the hosts
they're running on if there are no namespace-wide default resource
limits.
Unlike with memory requests/limits, limits are enforced at the CPU
scheduling level, so IIUC it's not possible to be evicted due to
excessive CPU usage.
So let's start defaulting to a reasonable not too large value and ensure
we set both the CPU requests and limits. This also allows cgroups-aware
applications to derive the correct number of "equivalent CPUs" to use
for multi-threaded/multi-processing steps.
> pod: set both the resource CPU request and limit

- vars/fcosKola.groovy
As of 7b552e1134, we're enforcing CPU resource limits on our pods.  The current defaults allocate 2 CPUs and then use them to run 8 parallel kola tests and a kola upgrade test.  Reduce oversubscription by having kola parallelize to the number of available CPUs by default.  There's still some oversubscription because we're running the kola upgrade test in parallel with that, but that currently only needs 1 CPU.
> fcosKola: parallelize kola to the number of CPUs

- vars/cosaPod.groovy
The canonical location is Quay.io again so let's use that so we don't
have to wait for app.ci to mirror it.
> cosaPod: point back to Quay.io for cosa

- resources/com/github/coreos/job.yaml
Since the role of the container here is super minimal let's just use the minimal container and also follow the :latest tag so that we don't ever have to worry about being on an EOL release.
> job.yaml: switch to minimal image; use :latest tag

- vars/pod.groovy
When deploying the RHCOS pipeline we ran into a case where there was a limitrange set with a default memory limit:
```
oc describe limitrange
Type        Resource  Min  Max  Default Request  Default Limit  Max Limit/Request Ratio
----        --------  ---  ---  ---------------  -------------  -----------------------
Container   cpu       -    -    300m             4              -
Container   memory    -    -    400Mi            6656Mi         -
```
In this case we also needed to bump the memory for the COSA pod to 8Gi. Bumping it to 8Gi (via cosaPod()) set the request but not the limit. The pod inherited the default limit of 6656 Mi and we got an error:
```
Invalid value: "8Gi": must be less than or equal to memory limit
```
Let's just set the limit to the same value as the request here. …
> pod: set memory limit also

- vars/tryWithCredentials.groovy
This new step can be used just like `withCredentials`, except that if the credentials don't exist, we'll gracefully return.
Upstreamed from the FCOS pipeline.
> Add `tryWithCredentials` custom step

- vars/kola.groovy
This effectively upstreams
https://github.com/coreos/fedora-coreos-pipeline/commit/c3af4ad57ab4.
The same reasons apply, but we're doing it now here too because it'll help with not hitting against our memory limits.
> kola: run provisioning tests separately

- vars/utils.groovy
This will be used by the pipeline to process some of the templated fields in `config.yaml`. Putting it here allows us to work around the fact that the `SimpleTemplateEngine` API would normally have to be allowed by an administrator first.
> utils: add substituteStr

- vars/cosaBuild.groovy
Commit 3719f69 ("tree: drop FCOS wording from various places") broke multiple upstream CI jobs which still reference the old location. We need to temporarily support both locations as we migrate them.
Add a compat symlink.
> vars/utils: add compat symlink from `/srv/fcos` to `/srv/coreos`

- vars/kola.groovy
- vars/kolaTestIso.groovy
```
commit 3c2aef4d73a320965c4628e29ec1780b31031ef3
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Thu Oct 13 11:37:31 2022 -0400
{kola,kolaTestIso}: make the collection of logs non-fatal
In case a test blew up for another reason let's not make the collection
of the logs tank the entire run.
commit fd6649aae6df02b3402ed7760b48a1abc32d6458
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Thu Oct 13 11:34:56 2022 -0400
{kola,kolaTestIso}: remove the unnecessary stage declaration
When nesting `parallel` calls like we do in the `bump-lockfile` job
in our FCOS pipeline the extra stage declaration confuses the Blue
Ocean view. Let's just drop it.
commit c16b3d04ee98998a6367ab89143c13d3b6dfd15f
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Thu Oct 13 00:43:26 2022 -0400
{kola,kolaTestIso}: …
```
> rework kola/kolaTestIso functions

- vars/kola.groovy
- vars/kolaTestIso.groovy
When using `dir()` in the kola and kolaTestIso jobs the cd is happening on the controller (not in the COSA pod) so if the directory isn't under the env.WORKSPACE directory then we get a permission denied error.
Let's go back to using a `cd ${cosaDir}` for now to workaround this while we find better solutions. This `cd ${cosaDir}` will have no effect on multi-arch where we'll be operating in a remote session anyway.
> {kola,kolaTestIso}: workaround issue with accessDenied from dir()

- vars/cosaBuild.groovy
- vars/fcosBuild.groovy
- vars/fcosKola.groovy
- vars/fcosKolaTestIso.groovy
All the repos have been updated now, so we can drop the compat symlinks.
> Delete compatibility symlinks for `fcos`-named things

- vars/kola.groovy
I think with 380ffa5 it makes the optimization from 362e995 no longer required. In it's current form the kola-azure and kola-openstack tests in the pipeline don't have the kola tests broken out into a separate stage (they skip the upgrade test) so it's hard to find a failure in the blue ocean view when one happens.
> kola: run with parallel even if single stage

- vars/utils.groovy
```
commit 2adcb5a885485871bf388ead4a472cc499e34a2d
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Wed Oct 19 12:06:20 2022 -0400
utils: add syncCredentialsIfInRemoteSession() helper
This will help us copy over credentials to the remote node if we're
inside a remote session. Having the code in a single place means we're
less likely to copy/paste and make mistakes.
commit 6b18a7b4e794561019a3c9f76927e5db06b4730d
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Wed Oct 19 12:05:46 2022 -0400
utils: add credentialsExist() helper
```
> utils: add some credential helpers

- vars/kola.groovy
- vars/kolaTestIso.groovy
If we pass the full directory name to `tar -c`, it'll want to recreate the whole structure on extracting. Instead, use `-C` so we only pass the final directory to `tar`. That'll ensure we still create at least one directory on extraction instead of filling up the working directory. We used to do this, but I think it got lost in the recent enhancements on these steps.
> kola/kolaTestIso: fix tar path

- vars/kola.groovy
- vars/kolaTestIso.groovy
This will be used by the pipeline when SecureBoot tests should be skipped (e.g. when testing an unsigned kernel).
> kola/kolaTestIso: support skipSecureBoot

- vars/withPodmanRemote.groovy
There is a regression in podman [1] that causes podman remote sessions to not work unless the port is specified. Let's just add the port so we can get unblocked.
[1] https://github.com/containers/podman/issues/16509
> withPodmanRemote: add port 22 to CONTAINER_HOST env var

- vars/kola.groovy
- vars/warn.groovy
We started using this convention in a few places in the pipeline. Let's add a helper for it. Make it top-level so it feels as ergonomic as an `error` call.
> Add warn helper

- vars/kola.groovy
This reverts commit 06425433fb9d87f1467681f428a26c51164e3c12.
This test should be fixed now by
https://github.com/coreos/coreos-assembler/pull/3266 and backports.
> Revert "kola: denylist rhcos.upgrade.from-ocp-rhcos for now"

- vars/kola.groovy
If the kola upgrade test fails early enough that logs werene't even created then we'll get a failure like:
```
10:50:22  + cosa shell -- test -d /home/jenkins/agent/workspace/build/tmp/kola-5JOIO/kola-upgrade
10:50:22  error: failed to execute cmd-shell: exit status 1
```
Let's try to remove the log from consideration if that's the case.
> kola: fix allowUpgradeFail by removing id from log check

- vars/shwrapCapture.groovy
- vars/shwrapRc.groovy
We had it in `shwrap`, but not `shwrapCapture` and `shwrapRc`. We're hitting an issue right now where `podman` wants to create `$HOME/.ssh` when using the remote stuff but because we're running unprivileged, we get
```
Error: failed to connect: ssh: handshake failed: mkdir /.ssh: permission denied
```
We're still trying to determine why this is new, but let's fix the inconsistency for now.
> Add `HOME` workaround to other shwrap helpers

- vars/pod.groovy
- vars/shwrap.groovy
- vars/shwrapCapture.groovy
- vars/shwrapRc.groovy
This reverts commit 3577892a9cac46964a5f44be8881a9ef7741df8c.
Setting the `HOME` var to the workspace from the pod definition doesn't work because it introduces a chicken-and-egg problem: the workspace isn't yet allocated since the pod isn't running yet.
This isn't a pure revert since I wanted to keep 33d4910 ("Add `umask` workaround to other shwrap helpers"), which came after.
> Revert "Set `HOME` at the pod level instead of in shwrap helpers"

- vars/kola.groovy
We'll start now to default to passing in --allow-rerun-success tags=needs-internet so that we can get notified less about intermittent network flakes.
If someone wants to disable this they can pass in allowRerunSuccess=false.
If someone wants to override the tags to use for rerun-success they can use allowRerunSuccessArgs. For example, allowRerunSuccessArgs="tags=all".
> kola: add support for allowRerunSuccess

- vars/kola.groovy
If we have a whitespace the parsing needle that we have to thread thread through cmd-kola into `kola run-upgrade` doesn't work right. We end up with:
```
[dustymabe@media fcos]$ cosa kola --rerun --allow-rerun-success tags=all --upgrades
kola -p qemu-unpriv tags=all --rerun --allow-rerun-success --output-dir tmp/kola-upgrade --qemu-image-dir tmp/kola-qemu-cache -v --find-parent-image
Error: unknown command "tags=all" for "kola"
Run 'kola --help' for usage.
2023-05-05 21:03:38.033149 C | cli: unknown command "tags=all" for "kola"
error: failed to execute cmd-kola: exit status 1
```
> kola: don't use whitespace in --allow-rerun-success option

- vars/pod.groovy
Allowing the caller to specify the pod name would make it easier to identify what pods were created for what purpose.
We are planning to use this in the debug pod pipeline job to allow users to identify which debug pods they own.
Ref: https://github.com/coreos/fedora-coreos-pipeline/issues/803
> pod: Allow caller to specify name of pod

- vars/kola.groovy
This commit refactors the arguments and error handling for `kola` into a runKola closure to make it easier to manage. Most calls in this file use mostly the same arguments, so this is a nice cleanup.
This commit also adds the `--on-warn-failure-exit-77` option [1] and adds handling to mark a test as `warn()` if that happens versus the typical `error()`.
[1] https://github.com/coreos/coreos-assembler/pull/3551
> kola: refactor and add support for warn: true tests

- vars/kola.groovy
Right now in the upgrade case we end up with `cosa kola run --upgrades`
and that doesn't quite pass through everything right:
```
+ cosa kola run --rerun --allow-rerun-success=tags=needs-internet --build=39.20230823.92.0 --output-dir=/home/jenkins/agent/workspace/kola-gcp/tmp/kola-UJ7JH/kola-upgrade --on-warn-failure-exit-77 --arch=x86_64 -p=gcp --gcp-json-key=**** --gcp-project=fedora-coreos-testing --upgrades
kola --build 39.20230823.92.0 run --rerun --allow-rerun-success=tags=needs-internet --on-warn-failure-exit-77 --arch=x86_64 -p=gcp --gcp-json-key=**** --gcp-project=fedora-coreos-testing --output-dir /home/jenkins/agent/workspace/kola-gcp/tmp/kola-UJ7JH/kola-upgrade --qemu-image-dir tmp/kola-qemu-cache -v --find-parent-image
Error: unknown flag: --qemu-image-dir
```
We need the …
> kola: specify action to runKola helper

- vars/kola.groovy
- vars/kolaTestIso.groovy
This will allow us to much more easily inspect failing kola tests. Goes together with https://github.com/coreos/coreos-assembler/pull/3667, which has more details.
While we're here, use `kola-testiso` as marker since it looks clearer and for consistency with `kola-upgrade`.
> kola/kolaTestIso: use `kola-junit` to publish JUnit test results

- vars/kola.groovy
The argument for --basic-qemu-scenarios has been removed. The tests invoked by it are now formal kola tests.
See https://github.com/coreos/coreos-assembler/pull/3652
> vars/kola: drop `--basic-qemu-scenarios`

- vars/kola.groovy
Introduce a kola parameter to allow skipping a list of kola tags. This is particularly useful when adding new streams to the pipeline.
xref: https://github.com/coreos/fedora-coreos-pipeline/pull/1008
See: https://github.com/coreos/fedora-coreos-pipeline/issues/1002
> vars/kola: Add support for skipping a list of kola tags

- vars/checkoutToDir.groovy
The extensions object's syntax here is incorrect:
> WARNING: Unknown parameter(s) found for class type 'hudson.plugins.git.extensions.impl.RelativeTargetDirectory': recursiveSubmodules
The `recursiveSubmodules` option is part of another extension type we need to add to the list.
> vars/checkoutToDir: fix checkout step syntax

- vars/kolaTestIso.groovy
- vars/withPodmanRemote.groovy
We've been seeing a lot of testiso flakes lately. Let's try to give ourselves a break by retrying like we do for normal kola runs.
This is slightly different because it's not done inside kola but outside kola. For the inside kola retry of testiso we'll wait for https://github.com/coreos/coreos-assembler/issues/3989 to happen.
> kolaTestIso: retry failed tests

- vars/kolaTestIso.groovy
Fixes b1f6e8a. If there are multiple test failures the newline in the output will mean only one test failure gets retried. This also means that the outputdir wasn't getting set right. Removing just the newline should fix both issues, but let's move the `--output-dir` option earlier in the command invocation anyway.
> kolaTestIso: Retry all testiso failures

- vars/cosaPod.groovy
The git info is already printed but having it be a proper archive makes it easier to access.
Also archive the full rpmdb package list.
> cosaPod: archive cosa git info and RPMs
